version: '2'
services:

    cassandra-seed1:
       image: cassandra
       container_name: cassandra-seed1
       hostname: cassandra-seed1
       restart: always
       ports:
          - "9042:9042"
       networks:
           - default_network

    cassandra-node:
       image: cassandra
       restart: always
       links:
           - cassandra-seed1:seed1
       environment:
           - CASSANDRA_SEEDS=seed1
       networks:
           - default_network

networks:
  default_network:
      external: true